book_list = [
    {
        "id": 1,
        "title": "Think Python",
        "page_count": 1234,
        "author": "Allen B. Downey",
        "language": "English",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
    },
    {
        "id": 2,
        "title": "Django By Example",
        "page_count": 1023,
        "author": "Anthony Mele",
        "language": "English",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2021-01-19",
    },
    {
        "id": 3,
        "title": "The Web socket handbook",
        "page_count": 1023,
        "author": "Alex Diaconu",
        "language": "English",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2020-02-09",
    },
    {
        "id": 4,
        "title": "Head First HTML5 Programming",
        "page_count": 3000,
        "author": "Eric T Freemab",
        "language": "English",
        "publisher": "O'Reilly Media",
        "published_date": "2011-7-01",
    },
    {
        "id": 5,
        "title": "Think and grow rich",
        "page_count": 300,
        "author": "Anthony Joshua",
        "language": "English",
        "publisher": "O'Reilly Media",
        "published_date": "2023-12-04",
    },
]
